### ISSUE TITLE
&

### ISSUE THREAD

**Issue by coderstory** [nian0114/port_h2os_gemini#2]
./../tools/sdat2img.py system.transfer.list system.new.dat system.img &> /dev/null
  sudo mount -t ext4 -o loop system.img output/

我不知道为什么你上传的脚本是这样的

后台分解system.new.dat  然后直接mount解压了不完整的system.img 是想干什么

**Comment by nian0114** [comment]
不影响 实际已经分解完全 否则你是挂不上ext4格式的img 只是没有输出到屏幕日志而已
